<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Ppip.AiWorker</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\building-blocks\Ppip.BuildingBlocks.Health\Ppip.BuildingBlocks.Health.csproj" />
    <ProjectReference Include="..\..\building-blocks\Ppip.BuildingBlocks.Observability\Ppip.BuildingBlocks.Observability.csproj" />
  </ItemGroup>
</Project>
