<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="NetArchTest.Rules" Version="1.*" />
    <PackageReference Include="xunit" Version="2.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\building-blocks\Ppip.BuildingBlocks.Domain\Ppip.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\..\src\building-blocks\Ppip.BuildingBlocks.Messaging\Ppip.BuildingBlocks.Messaging.csproj" />
    <ProjectReference Include="..\..\src\modules\procurement\Ppip.Procurement.Domain\Ppip.Procurement.Domain.csproj" />
  </ItemGroup>
</Project>
